repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: v22.1.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)